apiVersion: apps/v1
kind: Deployment
metadata:
  name: levelupdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: levelupdevops
  template:
    metadata:
      labels:
        app: levelupdevops
        version: IMAGE_LABEL
    spec:
      containers:
        - name: levelupdevops
          image: DOC_URL/backend_api:IMAGE_LABEL
          ports:
            - containerPort: 80
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: levelupdevops
spec:
  type: LoadBalancer
  selector:
    app: levelupdevops
  ports:
    - port: 80
      targetPort: 80
