# DEPRECATED by me, using docker.sock
# ***************************************************************************************



#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: dind
#  namespace: docker-in-docker
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#---
apiVersion: v1
kind: Service
metadata:
  name: dind
  namespace: oe-b2b-evs-dv
spec:
  type: ClusterIP
  selector:
    workload: deployment-docker-in-docker-dind
  ports:
    - name: dind
      port: 2376
      targetPort: 2376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  namespace: oe-b2b-evs-dv
spec:
  replicas: 1
  selector:
    matchLabels:
      workload: deployment-docker-in-docker-dind
  template:
    metadata:
      labels:
        workload: deployment-docker-in-docker-dind
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - command:
            - dockerd
            - --host=unix:///var/run/docker.sock
            - --host=tcp://0.0.0.0:2376
          env:
            - name: DOCKER_TLS_CERTDIR
            - name: harbor_url
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: harbor_url
            - name: harbor_username
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: harbor_username
            - name: harbor_password
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: harbor_password
          image: docker:19.03.12-dind
          imagePullPolicy: IfNotPresent
          name: dind
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          stdin: true
          tty: true
#          volumeMounts:
#            - mountPath: /var/lib/docker
#              name: dind-storage
#      volumes:
#        - name: dind-storage
#          persistentVolumeClaim:
#            claimName: dind