apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: oe-b2b-evs-dv
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run
      containers:
        - name: runner
          image: harbor.tsl.telus.com/oe-b2b-evs/ivs-runner:1.0.0-16
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          volumeMounts:
            - mountPath: /var/run
              name: docker-sock
          env:
            - name: DOCKER_HOST
              value: NULL
            - name: GITHUB_OWNER
              value: DanilZaitsev
            - name: GITHUB_REPOSITORY
              value: backend_api
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: GITHUB_PERSONAL_TOKEN
            - name: harbor_url
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: harbor_url
            - name: harbor_username
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: harbor_username
            - name: harbor_password
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: harbor_password
      imagePullSecrets:
        - name: regcred