apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: oe-b2b-evs-dv
type: Opaque
stringData:
  GITHUB_PERSONAL_TOKEN: test
  harbor_url: ''
  harbor_username: ''
  harbor_password: ''