name: Docker Build & Push, Kubernetes Apply

on:
  push:
    branches: 
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
          username: ${{ secrets.ECR_USERNAME }}
          password: ${{ secrets.ECR_PASSWORD }}
          
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          # Contents of kubeconfig file
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Docker build & push, Kubernetes apply
        run: |
          docker build -t ${{ secrets.DOC_URL }}/backend_api:${{ github.sha }} .
          docker push ${{ secrets.DOC_URL }}/backend_api:${{ github.sha }}
          sed -i'' -e 's/DOC_URL/${{ secrets.DOC_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
          kubectl apply -f k8s.yaml
