name: Docker Build & Push, Kubernetes Apply

on:
  push:
    branches: 
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v2.1
        with:
          # Version of kubectl
          version: latest # default is latest
          
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          # Contents of kubeconfig file
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
    
      - name: Docker build & push, Kubernetes apply
        run: |
          docker login ${{ secrets.ECR_REGISTRY }} --username ${{ secrets.ECR_USERNAME }} --password ${{ secrets.ECR_PASSWORD }}
          docker build -t ${{ secrets.DOC_URL }}/backend_api:${{ github.sha }} .
          docker push ${{ secrets.DOC_URL }}/backend_api:${{ github.sha }}
          sed -i'' -e 's/DOC_URL/${{ secrets.DOC_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
          kubectl apply -f k8s.yaml
