name: Docker Build & Push, Kubernetes Apply

on:
  push:
    branches: 
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2    
      - name: Docker build & push, Kubernetes apply
        run: |
          sudo docker build -t harbor.tsl.telus.com/oe-b2b-evs/ivs-runner:test .
          sudo docker push harbor.tsl.telus.com/oe-b2b-evs/ivs-runner:test
